export const REQUEST_TEAMS = 'REQUEST_TEAMS'

export const RECEIVE_TEAMS = 'RECEIVE_TEAMS'

export const RECEIVE_TEAMS_FAILED = 'RECEIVE_TEAMS_FAILED'

export const VOTE_FOR_TEAMS = 'VOTE_FOR_TEAMS'

export const VOTE_FOR_TEAMS_SUCCEED = 'VOTE_FOR_TEAMS_SUCCEED'

export const VOTE_FOR_TEAMS_FAILED = 'VOTE_FOR_TEAMS_FAILED'

export const REQUEST_VOTER_STATUS = 'REQUEST_VOTER_STATUS'

export const RECEIVE_VOTER_STATUS = 'RECEIVE_VOTER_STATUS'

export const RECEIVE_VOTER_STATUS_FAILED = 'RECEIVE_VOTER_STATUS_FAILED'
