export const REQUEST_TEAMS = 'REQUEST_TEAMS'

export const RECEIVE_TEAMS = 'RECEIVE_TEAMS'

export const RECEIVE_TEAMS_FAILED = 'RECEIVE_TEAMS_FAILED'

export const REQUEST_VOTER_STATUS = 'REQUEST_VOTER_STATUS'

export const RECEIVE_VOTER_STATUS = 'RECEIVE_VOTER_STATUS'

export const RECEIVE_VOTER_STATUS_FAILED = 'RECEIVE_VOTER_STATUS_FAILED'

export const SELECT_TEAM = 'SELECT_TEAM'

export const UN_SELECT_TEAM = 'UN_SELECT_TEAM'

export const POST_VOTING = 'POST_VOTING'

export const POST_VOTING_SUCCESS = 'POST_VOTING_SUCCESS'

export const POST_VOTING_FAILED = 'POST_VOTING_FAILED'
